/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/grieshaber/generic-autoscaler-controller/pkg/apis/autoscalingrule/v1"
	scheme "github.com/grieshaber/generic-autoscaler-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AutoscalingRulesGetter has a method to return a AutoscalingRuleInterface.
// A group's client should implement this interface.
type AutoscalingRulesGetter interface {
	AutoscalingRules(namespace string) AutoscalingRuleInterface
}

// AutoscalingRuleInterface has methods to work with AutoscalingRule resources.
type AutoscalingRuleInterface interface {
	Create(*v1.AutoscalingRule) (*v1.AutoscalingRule, error)
	Update(*v1.AutoscalingRule) (*v1.AutoscalingRule, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AutoscalingRule, error)
	List(opts metav1.ListOptions) (*v1.AutoscalingRuleList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AutoscalingRule, err error)
	AutoscalingRuleExpansion
}

// autoscalingRules implements AutoscalingRuleInterface
type autoscalingRules struct {
	client rest.Interface
	ns     string
}

// newAutoscalingRules returns a AutoscalingRules
func newAutoscalingRules(c *BsinfoV1Client, namespace string) *autoscalingRules {
	return &autoscalingRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the autoscalingRule, and returns the corresponding autoscalingRule object, and an error if there is any.
func (c *autoscalingRules) Get(name string, options metav1.GetOptions) (result *v1.AutoscalingRule, err error) {
	result = &v1.AutoscalingRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("autoscalingrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AutoscalingRules that match those selectors.
func (c *autoscalingRules) List(opts metav1.ListOptions) (result *v1.AutoscalingRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AutoscalingRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("autoscalingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested autoscalingRules.
func (c *autoscalingRules) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("autoscalingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a autoscalingRule and creates it.  Returns the server's representation of the autoscalingRule, and an error, if there is any.
func (c *autoscalingRules) Create(autoscalingRule *v1.AutoscalingRule) (result *v1.AutoscalingRule, err error) {
	result = &v1.AutoscalingRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("autoscalingrules").
		Body(autoscalingRule).
		Do().
		Into(result)
	return
}

// Update takes the representation of a autoscalingRule and updates it. Returns the server's representation of the autoscalingRule, and an error, if there is any.
func (c *autoscalingRules) Update(autoscalingRule *v1.AutoscalingRule) (result *v1.AutoscalingRule, err error) {
	result = &v1.AutoscalingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("autoscalingrules").
		Name(autoscalingRule.Name).
		Body(autoscalingRule).
		Do().
		Into(result)
	return
}

// Delete takes name of the autoscalingRule and deletes it. Returns an error if one occurs.
func (c *autoscalingRules) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("autoscalingrules").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *autoscalingRules) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("autoscalingrules").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched autoscalingRule.
func (c *autoscalingRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AutoscalingRule, err error) {
	result = &v1.AutoscalingRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("autoscalingrules").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
