kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: generic-autoscaler-controller
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: generic-autoscaler-controller
    spec:
      containers:
        - name: generic-autoscaler-controller-container
          image: freddyfroehlich/generic-autoscaler-controller:latest
      imagePullSecrets:
        - name: regcred
