apiVersion: v1
kind: Namespace
metadata:
  name: autoscaling
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: gac
  namespace: autoscaling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gac-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-metrics-server-resources
subjects:
  - kind: ServiceAccount
    name: gac
    namespace: autoscaling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-access
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-access
rules:
  - apiGroups: ["bsinfo.hhu.de"]
    resources: ["autoscalingrules"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gac-resource-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployment-access
subjects:
  - kind: ServiceAccount
    name: gac
    namespace: autoscaling
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gac-crd-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-access
subjects:
  - kind: ServiceAccount
    name: gac
    namespace: autoscaling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gac-deployment
  namespace: autoscaling
  labels:
    app: generic-autoscaler-controller
spec:
  selector:
    matchLabels:
      app: generic-autoscaler-controller
  template:
    metadata:
      labels:
        app: generic-autoscaler-controller
    spec:
      serviceAccountName: gac
      containers:
        - name: generic-autoscaler-controller-container
          image: freddyfroehlich/generic-autoscaler-controller:latest
      imagePullSecrets:
        - name: regcred
