/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	autoscalingrulev1 "github.com/grieshaber/generic-autoscaler-controller/pkg/apis/autoscalingrule/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAutoscalingRules implements AutoscalingRuleInterface
type FakeAutoscalingRules struct {
	Fake *FakeBsinfoV1
	ns   string
}

var autoscalingrulesResource = schema.GroupVersionResource{Group: "bsinfo.hhu.de", Version: "v1", Resource: "autoscalingrules"}

var autoscalingrulesKind = schema.GroupVersionKind{Group: "bsinfo.hhu.de", Version: "v1", Kind: "AutoscalingRule"}

// Get takes name of the autoscalingRule, and returns the corresponding autoscalingRule object, and an error if there is any.
func (c *FakeAutoscalingRules) Get(name string, options v1.GetOptions) (result *autoscalingrulev1.AutoscalingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(autoscalingrulesResource, c.ns, name), &autoscalingrulev1.AutoscalingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingrulev1.AutoscalingRule), err
}

// List takes label and field selectors, and returns the list of AutoscalingRules that match those selectors.
func (c *FakeAutoscalingRules) List(opts v1.ListOptions) (result *autoscalingrulev1.AutoscalingRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(autoscalingrulesResource, autoscalingrulesKind, c.ns, opts), &autoscalingrulev1.AutoscalingRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &autoscalingrulev1.AutoscalingRuleList{ListMeta: obj.(*autoscalingrulev1.AutoscalingRuleList).ListMeta}
	for _, item := range obj.(*autoscalingrulev1.AutoscalingRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested autoscalingRules.
func (c *FakeAutoscalingRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(autoscalingrulesResource, c.ns, opts))

}

// Create takes the representation of a autoscalingRule and creates it.  Returns the server's representation of the autoscalingRule, and an error, if there is any.
func (c *FakeAutoscalingRules) Create(autoscalingRule *autoscalingrulev1.AutoscalingRule) (result *autoscalingrulev1.AutoscalingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(autoscalingrulesResource, c.ns, autoscalingRule), &autoscalingrulev1.AutoscalingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingrulev1.AutoscalingRule), err
}

// Update takes the representation of a autoscalingRule and updates it. Returns the server's representation of the autoscalingRule, and an error, if there is any.
func (c *FakeAutoscalingRules) Update(autoscalingRule *autoscalingrulev1.AutoscalingRule) (result *autoscalingrulev1.AutoscalingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(autoscalingrulesResource, c.ns, autoscalingRule), &autoscalingrulev1.AutoscalingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingrulev1.AutoscalingRule), err
}

// Delete takes name of the autoscalingRule and deletes it. Returns an error if one occurs.
func (c *FakeAutoscalingRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(autoscalingrulesResource, c.ns, name), &autoscalingrulev1.AutoscalingRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAutoscalingRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(autoscalingrulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &autoscalingrulev1.AutoscalingRuleList{})
	return err
}

// Patch applies the patch and returns the patched autoscalingRule.
func (c *FakeAutoscalingRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *autoscalingrulev1.AutoscalingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(autoscalingrulesResource, c.ns, name, pt, data, subresources...), &autoscalingrulev1.AutoscalingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingrulev1.AutoscalingRule), err
}
