// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoMode) DeepCopyInto(out *AutoMode) {
	*out = *in
	in.Limits.DeepCopyInto(&out.Limits)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoMode.
func (in *AutoMode) DeepCopy() *AutoMode {
	if in == nil {
		return nil
	}
	out := new(AutoMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingRule) DeepCopyInto(out *AutoscalingRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingRule.
func (in *AutoscalingRule) DeepCopy() *AutoscalingRule {
	if in == nil {
		return nil
	}
	out := new(AutoscalingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingRuleList) DeepCopyInto(out *AutoscalingRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoscalingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingRuleList.
func (in *AutoscalingRuleList) DeepCopy() *AutoscalingRuleList {
	if in == nil {
		return nil
	}
	out := new(AutoscalingRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingRuleSpec) DeepCopyInto(out *AutoscalingRuleSpec) {
	*out = *in
	out.Modes = in.Modes
	in.Thresholds.DeepCopyInto(&out.Thresholds)
	in.AutoMode.DeepCopyInto(&out.AutoMode)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingRuleSpec.
func (in *AutoscalingRuleSpec) DeepCopy() *AutoscalingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Limits) DeepCopyInto(out *Limits) {
	*out = *in
	out.UpperLimit = in.UpperLimit.DeepCopy()
	out.LowerLimit = in.LowerLimit.DeepCopy()
	out.DesiredUsage = in.DesiredUsage.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Limits.
func (in *Limits) DeepCopy() *Limits {
	if in == nil {
		return nil
	}
	out := new(Limits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Modes) DeepCopyInto(out *Modes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Modes.
func (in *Modes) DeepCopy() *Modes {
	if in == nil {
		return nil
	}
	out := new(Modes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Thresholds) DeepCopyInto(out *Thresholds) {
	*out = *in
	out.UpperThreshold = in.UpperThreshold.DeepCopy()
	out.LowerThreshold = in.LowerThreshold.DeepCopy()
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Thresholds.
func (in *Thresholds) DeepCopy() *Thresholds {
	if in == nil {
		return nil
	}
	out := new(Thresholds)
	in.DeepCopyInto(out)
	return out
}
