apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: autoscalingrules.bsinfo.hhu.de
  namespace: autoscaling
spec:
  group: bsinfo.hhu.de
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: autoscalingrules
    singular: autoscalingrule
    kind: AutoscalingRule
    shortNames:
      - asr
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            targetNamespace:
              type: string
            metricName:
              type: string
            priority:
              type: integer
              minimum: 1
              maximum: 5
            modes:
              type: object
              properties:
                upscaling:
                  type: string
                downscaling:
                  type: string
            thresholds:
              type: object
              properties:
                upperThreshold:
                  type: string
                lowerThreshold:
                  type: string
                maxViolationCount:
                  type: integer
                  minimum: 1
            autoMode:
              type: object
              properties:
                deltaMetric:
                  type: string
                valueMetric:
                  type: string
                limits:
                  type: object
                  properties:
                    upperLimit:
                      type: string
                    lowerLimit:
                      type: string
                    desiredUsage:
                      type: string
                    maxViolationCount:
                      type: integer
                      minimum: 1
          oneOf:
            - required: ["modes", "metricName", "thresholds"]
            - required: ["autoMode"]
      required: ["spec"]
