apiVersion: bsinfo.hhu.de/v1
kind: AutoscalingRule
metadata:
  name: memory-usage-rule
  namespace: autoscaling
spec:
  targetNamespace: workload-sim
  metricName: de_hhu_bsinfo_Storage_MemoryUsage
  modes:
    upscaling: strong
    downscaling: medium
  priority: 5
  thresholds:
    upperThreshold: 800m
    lowerThreshold: 400m
    maxViolationCount: 3