apiVersion: bsinfo.hhu.de/v1
kind: AutoscalingRule
metadata:
  name: memory-usage-rule
  namespace: autoscaling
spec:
  targetNamespace: aerospike
  metricName: aerospike_ns_memory_usage
  modes:
    upscaling: mild
    downscaling: mild
  priority: 5
  thresholds:
    upperThreshold: 800m
    lowerThreshold: 400m
    maxViolationCount: 3